### ISSUE TITLE
Potentially unhandled rejection [1] TypeError: Cannot set property 'queueName' of undefined

### ISSUE THREAD

**Issue by AlexZeitler** [mateodelnorte/servicebus#72]
In a service using servicebus (tried 1.0.21, 1.0.19 and 1.0.18) I'm receiving this console output and I'm not sure why:

```
Potentially unhandled rejection [1] TypeError: Cannot set property 'queueName' of undefined
    at RabbitMQBus.setOptions (/app/node_modules/servicebus/bus/rabbitmq/bus.js:161:23)
    at RabbitMQBus.subscribe (/app/node_modules/servicebus/bus/rabbitmq/bus.js:221:8)
    at emitNone (events.js:91:20)
    at RabbitMQBus.emit (events.js:185:7)
    at done (/app/node_modules/servicebus/bus/rabbitmq/bus.js:56:14)
    at /app/node_modules/servicebus/bus/rabbitmq/bus.js:77:7
    at tryCatchReject (/app/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/app/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/app/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/app/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/app/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/app/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by AlexZeitler** [comment]
Never mind: the handler function passed to `bus.subscribe()` did not exist.
